const logoMaping: { [key: string]: string } = {
  '201': 'internet_default.jpg',
  '203': 'internet_htv_tms.png',
  '205': 'internet_vnpt_hcm.png',
  '206': 'internet_spt.png',
  '207': 'internet_newlife.png',
  '209': 'internet_vnpt_cantho.png',
  '210': 'internet_vnpt_danang.png',
  '211': 'internet_vnpt_hanoi.png',
  '208': 'internet_viettel.png',
  '272': 'internet_viettel.png',
  '204': 'internet_sctv.png',
  '270': 'internet_htv_tms.png',
  '273': 'internet_htv_tms.png',
  '274': 'internet_htv_tms.png',
  '275': 'internet_htv_tms.png',
  '276': 'internet_htv_tms.png',
  '277': 'internet_htv_tms.png',
  '278': 'internet_htv_tms.png',
  '279': 'internet_htv_tms.png',
  '280': 'internet_htv_tms.png',
  '281': 'internet_htv_tms.png',
  '282': 'internet_htv_tms.png',
  '283': 'internet_htv_tms.png',
  '284': 'internet_htv_tms.png',
  '285': 'internet_htv_tms.png',
  '286': 'internet_htv_tms.png',
  '287': 'internet_htv_tms.png',
  '20': 'internet_viettel.png',
  '4': 'internet_htv_tms.png',
  default: 'internet_htv_tms.png',
}

export default logoMaping
