server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;
  etag off;
  add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
  location / {
    try_files $uri /index.html;
  }
}
